### ISSUE TITLE
Upgrade to jprotoc 0.8.1 introduced IllegalArgumentException to my build

### ISSUE THREAD

**Issue by wfhartford** [rouzwawi/grpc-kotlin#17]
I've filed a bug upstream at https://github.com/salesforce/grpc-java-contrib/issues/91. As mentioned there, I'll take some time tomorrow to do investigate and try to produce a minimal reproducing project.

The error output is:
```
  java.lang.IllegalArgumentException: Multiple entries with same key: .google.protobuf.Type=com.google.protobuf.DescriptorProtos.Type and .google.protobuf.Type=com.google.protobuf.Type
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:100)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:86)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:300)
        at com.salesforce.jprotoc.ProtoTypeMap.of(ProtoTypeMap.java:69)
        at io.rouz.grpc.kotlin.GrpcKotlinGenerator.generate(GrpcKotlinGenerator.java:65)
        at com.salesforce.jprotoc.ProtocPlugin.lambda$generate$0(ProtocPlugin.java:77)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:86)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:45)
        at com.salesforce.jprotoc.ProtocPlugin.generate(ProtocPlugin.java:37)
        at io.rouz.grpc.kotlin.GrpcKotlinGenerator.main(GrpcKotlinGenerator.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
  --grpc-kotlin_out: protoc-gen-grpc-kotlin: Plugin failed with status code 1.
```

**Comment by wfhartford** [comment]
See my comment here: https://github.com/salesforce/grpc-java-contrib/issues/91#issuecomment-434382146

**Comment by rmichela** [comment]
Ok. I've been digging into this. Sorry for the delay. I had a baby shortly after this bug was submitted. 👶 🍼

The problem is ultimately caused by a behavior of protobuf-gradle-plugin. Swap the protobuf dependency to a compile dependency. When a protobuf dependency is used, protobuf-gradle-plugin ends up passing the standard protobuf protos to protoc twice, once through the extracted-protos directory and once through the extracted-include-protos.

This behavior has always been there and is arguably correct for protobuf-gradle-plugin. I'm still digging into why jprotoc started having problems.
